# Generated by Django 5.1.5 on 2025-04-02 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_utilisateur_color_1_utilisateur_color_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='in_tournament',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Tournoi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('players', models.JSONField(default=list)),
                ('tournament_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('whichRound', models.IntegerField(default=0)),
                ('winnerRound1', models.JSONField(default=list)),
                ('winnerRound2', models.JSONField(default=list)),
                ('winnerLastRound', models.CharField(default='', max_length=255)),
                ('looserRound1', models.JSONField(default=list)),
                ('looserRound2', models.JSONField(default=list)),
                ('looserLastRound', models.CharField(default='', max_length=255)),
                ('player1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournois_p1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
