# Generated by Django 5.1.5 on 2025-04-02 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_utilisateur_in_tournament_tournoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='tournamentRound',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='tournament_id',
            field=models.IntegerField(default=-1),
        ),
    ]
